# Generated by Django 2.2 on 2020-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20200901_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='body',
        ),
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.TextField(),
        ),
    ]
